baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Rayco Haex Portfolio'
primary: true
siteGroup: 826b69bf-5b92-46ff-9cfb-3546c5bc2a6d # Rayco Haex Portfolio
sortOrder: 1
