contentColumnType: string
fieldGroup: f458581b-16d2-42ae-9974-cd5312bebc25 # Common
handle: cvUrlNl
instructions: ''
name: 'cv url nl'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - pdf
    - word
  defaultUploadLocationSource: 'volume:a48f08d7-4dd6-4ecb-a627-9d347eb60749' # Files
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:391df726-69a9-45b1-b5bc-38e31475940b' # Project images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
