contentColumnType: string
fieldGroup: c5025c67-2da7-4194-9ccc-8e4660bd4118 # project
handle: projectThumbnail
instructions: ''
name: 'Project thumbnail'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:391df726-69a9-45b1-b5bc-38e31475940b' # Project images
  defaultUploadLocationSubpath: ''
  limit: ''
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Project image thumbnail'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:391df726-69a9-45b1-b5bc-38e31475940b' # Project images
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
